"""Add CircuitTopology table

Revision ID: 1f4415891af2
Revises: 4a48a3e95445
Create Date: 2026-06-19 16:50:15.661667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1f4415891af2'
down_revision: Union[str, Sequence[str], None] = '4a48a3e95445'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circuittopology',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('difficulty', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('num_gates', sa.Integer(), nullable=False),
    sa.Column('topology_data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('circuittopology', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_circuittopology_difficulty'), ['difficulty'], unique=False)
        batch_op.create_index(batch_op.f('ix_circuittopology_num_gates'), ['num_gates'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('circuittopology', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_circuittopology_num_gates'))
        batch_op.drop_index(batch_op.f('ix_circuittopology_difficulty'))

    op.drop_table('circuittopology')
    # ### end Alembic commands ###
