"""Rename to Mode2CircuitTopology

Revision ID: 9340105d4a8e
Revises: 1f4415891af2
Create Date: 2026-06-19 17:23:22.107006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9340105d4a8e'
down_revision: Union[str, Sequence[str], None] = '1f4415891af2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mode2circuittopology',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('difficulty', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('num_gates', sa.Integer(), nullable=False),
    sa.Column('topology_data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mode2circuittopology', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mode2circuittopology_difficulty'), ['difficulty'], unique=False)
        batch_op.create_index(batch_op.f('ix_mode2circuittopology_num_gates'), ['num_gates'], unique=False)

    with op.batch_alter_table('circuittopology', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_circuittopology_difficulty'))
        batch_op.drop_index(batch_op.f('ix_circuittopology_num_gates'))

    op.drop_table('circuittopology')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circuittopology',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('difficulty', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('num_gates', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('topology_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('circuittopology_pkey'))
    )
    with op.batch_alter_table('circuittopology', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_circuittopology_num_gates'), ['num_gates'], unique=False)
        batch_op.create_index(batch_op.f('ix_circuittopology_difficulty'), ['difficulty'], unique=False)

    with op.batch_alter_table('mode2circuittopology', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mode2circuittopology_num_gates'))
        batch_op.drop_index(batch_op.f('ix_mode2circuittopology_difficulty'))

    op.drop_table('mode2circuittopology')
    # ### end Alembic commands ###
