"""add_matches_table

Revision ID: adaa366e30a9
Revises: 9340105d4a8e
Create Date: 2026-06-20 13:04:23.753202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'adaa366e30a9'
down_revision: Union[str, Sequence[str], None] = '9340105d4a8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mode', sa.Integer(), nullable=False),
    sa.Column('player1_id', sa.Uuid(), nullable=False),
    sa.Column('player2_id', sa.Uuid(), nullable=True),
    sa.Column('is_bot_match', sa.Boolean(), nullable=False),
    sa.Column('is_friend_match', sa.Boolean(), nullable=False),
    sa.Column('player1_score', sa.Integer(), nullable=False),
    sa.Column('player2_score', sa.Integer(), nullable=False),
    sa.Column('winner_id', sa.Uuid(), nullable=True),
    sa.Column('result', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('player1_elo_before', sa.Integer(), nullable=False),
    sa.Column('player1_elo_after', sa.Integer(), nullable=False),
    sa.Column('player2_elo_before', sa.Integer(), nullable=False),
    sa.Column('player2_elo_after', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('match_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['player1_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['player2_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matches_mode'), ['mode'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_player1_id'), ['player1_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_player2_id'), ['player2_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matches_player2_id'))
        batch_op.drop_index(batch_op.f('ix_matches_player1_id'))
        batch_op.drop_index(batch_op.f('ix_matches_mode'))

    op.drop_table('matches')
    # ### end Alembic commands ###
