"""Add Mode3 puzzle metadata and DailyPuzzleAttempt table

Revision ID: c14e450938fc
Revises: d91c002c3b39
Create Date: 2026-06-22 01:30:02.199886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c14e450938fc'
down_revision: Union[str, Sequence[str], None] = 'd91c002c3b39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_puzzle_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('puzzle_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_date', sa.Date(), nullable=False),
    sa.Column('solve_time_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['puzzle_id'], ['mode3_puzzles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'attempt_date', name='uix_user_daily_attempt')
    )
    with op.batch_alter_table('daily_puzzle_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_puzzle_attempts_attempt_date'), ['attempt_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_puzzle_attempts_puzzle_id'), ['puzzle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_puzzle_attempts_solve_time_ms'), ['solve_time_ms'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_puzzle_attempts_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('mode3_puzzles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grid_width', sa.Integer(), nullable=False, server_default='3'))
        batch_op.add_column(sa.Column('grid_height', sa.Integer(), nullable=False, server_default='3'))
        batch_op.add_column(sa.Column('num_gates', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('num_holes', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('bit_width', sa.Integer(), nullable=False, server_default='2'))
        batch_op.create_index(batch_op.f('ix_mode3_puzzles_bit_width'), ['bit_width'], unique=False)
        batch_op.create_index(batch_op.f('ix_mode3_puzzles_grid_height'), ['grid_height'], unique=False)
        batch_op.create_index(batch_op.f('ix_mode3_puzzles_grid_width'), ['grid_width'], unique=False)
        batch_op.create_index(batch_op.f('ix_mode3_puzzles_num_gates'), ['num_gates'], unique=False)
        batch_op.create_index(batch_op.f('ix_mode3_puzzles_num_holes'), ['num_holes'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mode3_puzzles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mode3_puzzles_num_holes'))
        batch_op.drop_index(batch_op.f('ix_mode3_puzzles_num_gates'))
        batch_op.drop_index(batch_op.f('ix_mode3_puzzles_grid_width'))
        batch_op.drop_index(batch_op.f('ix_mode3_puzzles_grid_height'))
        batch_op.drop_index(batch_op.f('ix_mode3_puzzles_bit_width'))
        batch_op.drop_column('bit_width')
        batch_op.drop_column('num_holes')
        batch_op.drop_column('num_gates')
        batch_op.drop_column('grid_height')
        batch_op.drop_column('grid_width')

    with op.batch_alter_table('daily_puzzle_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_puzzle_attempts_user_id'))
        batch_op.drop_index(batch_op.f('ix_daily_puzzle_attempts_solve_time_ms'))
        batch_op.drop_index(batch_op.f('ix_daily_puzzle_attempts_puzzle_id'))
        batch_op.drop_index(batch_op.f('ix_daily_puzzle_attempts_attempt_date'))

    op.drop_table('daily_puzzle_attempts')
    # ### end Alembic commands ###
