"""Add Mode3Puzzle table

Revision ID: d91c002c3b39
Revises: adaa366e30a9
Create Date: 2026-06-22 00:37:24.433431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'd91c002c3b39'
down_revision: Union[str, Sequence[str], None] = 'adaa366e30a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mode3_puzzles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('difficulty', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('puzzle_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_daily', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mode3_puzzles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mode3_puzzles_difficulty'), ['difficulty'], unique=False)
        batch_op.create_index(batch_op.f('ix_mode3_puzzles_is_daily'), ['is_daily'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mode3_puzzles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mode3_puzzles_is_daily'))
        batch_op.drop_index(batch_op.f('ix_mode3_puzzles_difficulty'))

    op.drop_table('mode3_puzzles')
    # ### end Alembic commands ###
